# Generated by Django 4.2.11 on 2024-05-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_publish_date_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='book_photo', verbose_name='이미지'),
        ),
    ]
