# Generated by Django 4.2.11 on 2024-05-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_book_u_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='u_author',
            new_name='creater',
        ),
    ]
