# Generated by Django 4.2.11 on 2024-05-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('author', models.CharField(max_length=10, verbose_name='저자')),
                ('contents', models.TextField(default='', verbose_name='내용')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='출판일')),
            ],
        ),
    ]
