# Generated by Django 4.2.11 on 2024-05-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publish_date',
            new_name='created_at',
        ),
    ]
