# Generated by Django 5.0.3 on 2024-05-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_alter_post_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bookmark',
            new_name='bookmark_user',
        ),
    ]
