# Generated by Django 5.0.6 on 2024-05-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, verbose_name='평균 등급'),
        ),
    ]
