# Generated by Django 4.2.13 on 2024-05-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_post_body_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='구매 장소 / 가격을 포함하여 리뷰해주세요', verbose_name='리뷰'),
        ),
    ]
