# Generated by Django 4.2.13 on 2024-05-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_post_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_users',
        ),
    ]
